info:
  id: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  context-path: /management  

---
# For deployment in Docker containers      
spring:
  profiles: docker  
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 80
