info:
  id: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:  
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user    

management:
  context-path: /management  

---
# For deployment in Docker containers      
spring:
  profiles: docker  

server:
  port: 80

security:  
  oauth2:
    resource:
      userInfoUri: http://10.254.10.11:80/uaa/user    
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

ribbon:
  eureka:
   enabled: false

#Lista de Servicos############################      
auth-service:
  ribbon:
    listOfServers: http://10.254.10.11

user-admin-service:
  ribbon:
    listOfServers: http://10.254.10.12

provincia-service:
  ribbon:
    listOfServers: http://10.254.11.10
##############################################
