info:
  id: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:  
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user    

management:
  context-path: /management  

---
# For deployment in Docker containers      
spring:
  profiles: docker  
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 80
  
security:  
  oauth2:
    resource:
      userInfoUri: http://10.254.10.11:80/uaa/user    
