server:
  port: 8000

message: HELLO WORLD AGAIN

spring:
  cloud:
    stream:
      bindings:
        input:reservations
  eureka:
    instance:
      prefer-ip-address: true
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://${DOCKER_IP:discovery-service}:8761/eureka/