spring:
  application:
    name: reservation-client
  eureka:
    instance:
      non-secure-port: 8787
      prefer-ip-address: true
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://discovery-service:8761/eureka/    